name: Deploy

on:
  push:
    tags:
      - 'v*'      # v1.0.0, v1.2.3, etc.
      # or use '*' for all tags

jobs:
  deploy:
    runs-on: infra
    container:
      image: ubuntu:latest # or node:18, alpine:latest, etc.    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pause
        run: |
          sleep 15
          
      - name: Show tag
        run: |
          echo "Tag: ${{ github.ref_name }}"
